version: 2.1

notify:
  webhook:
    - url: https://outlook.office.com/webhook/4822921a-8a23-4a39-a98b-851a641ad2bf@8361af35-0fd9-4a74-ada4-aff5c74e7d0c/CircleCI/bc9fe4c36fa6445cbd0fd236c6a6c4c0/03960aaf-b3bf-4a9d-afd5-50a7ddbea283

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Install native build tools
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg dpkg-dev fakeroot rpm

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: yarn workspace client package-ci

      - store_artifacts:
          path: ~/repo/release/*.rpm

      - store_artifacts:
          path: ~/repo/release/*.deb
