version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.2

workflows:
  build:
    jobs:
      - build
  publish:
    jobs:
      - release
        requires:
          - build
          tags:
            only: v/^\d+\.\d+\.\d+$/


jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install native build tools
          command: |
            sudo apt-get update -y
            sudo apt-get install -y --no-install-recommends dpkg dpkg-dev fakeroot rpm python2.7
      - run:
          name: Install dependencies
          command: yarn --link-duplicates --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Compile build
          command: |
            # Deployment script
            yarn workspace client package-ci
            # Notify rollbar
            curl https://api.rollbar.com/api/1/deploy/ \
            -F access_token=$ROLLBAR_TOKEN \
            -F environment=production \
            -F revision=$CIRCLE_SHA1 \
            -F rollbar_username=jhdcruz \
            -F local_username=$CIRCLE_USERNAME
      - store_artifacts:
          path: ~/repo/release/
  #     - codecov/upload:
  #         file: coverage

  release:
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
