version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
#  codecov: codecov/codecov@1.0.2

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - run:
          name: Install native build tools
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg dpkg-dev fakeroot rpm
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Compile build
          command: yarn workspace client package-ci
      - store_artifacts:
          path: ~/repo/release/
#     - codecov/upload:
#         file: coverage

