version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.2

#workflows:
#  main:
#    jobs:
#      - build:

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update Yarn
          command: 'sudo npm update -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install native build tools
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg dpkg-dev fakeroot rpm python2
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Compile build
          command: yarn package-ci
      - store_artifacts:
          path: ~/repo/release/
#     - codecov/upload:
#         file: coverage

