name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux_osx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm python2.7
      - run: npm i -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn package-ci
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #      - name: Archive production artifacts
  #        uses: actions/upload-artifact@v2.2.0
  #        with:
  #          name: desktop installers
  #          path: client/release/*

  win:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: choco install python2 && refreshenv
      - run: npm i -g yarn msbuild
      - run: yarn
      - run: yarn lint
      - run: yarn package-win
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
  #      - name: Archive production artifacts
  #        uses: actions/upload-artifact@v2.2.0
  #        with:
  #          name: desktop installers
  #          path: client/release/*
