name: Desktop Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 15 ]

    steps:
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools
      - run: sudo apt-get install --no-install-recommends -y rpm
      - run: npm i -g yarn
      - run: yarn
      - run: yarn workspace client lint
      - run: yarn workspace client package-ci
      - name: Upload build artifacts
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: os-installers
          path: client/release/*
