name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Cache node_modules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
          with:
            path: ~/.yarn-cache
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools
      - run: sudo apt-get install --no-install-recommends -y rpm
      - run: npm i -g yarn
      - run: yarn
      - run: yarn workspace client lint
      - run: yarn workspace client package-linux
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: desktop installers
          path: client/release/*

  osx:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 15 ]

    steps:
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Cache node_modules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
          with:
            path: ~/.yarn-cache
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: yarn
      - run: yarn workspace client lint
      - run: yarn workspace client package-mac
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: desktop installers
          path: client/release/*

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 15 ]

    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/checkout@v2
      - uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_ACTION }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Cache node_modules
          uses: actions/cache@v2
          env:
            cache-name: cache-node-modules
          with:
            path: ~/.yarn-cache
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: yarn
      - run: yarn workspace client lint
      - run: yarn workspace client package-win
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: desktop installers
          path: client/release/*
