name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools
      - run: sudo apt-get install --no-install-recommends -y rpm
      - run: npm i -g yarn
      - run: yarn
      - run: yarn workspace client lint
      - run: yarn workspace client package-linux
      - uses: toko-bifrost/ms-teams-deploy-card@master
          if: always()
          with:
            github-token: ${{ secrets.GH_ACTION }}
            webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
