name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g yarn
      - run: yarn
      - run: yarn workspace client lint
      - run: yarn workspace client package-win
      - name: MS Teams Notifier
          uses: toko-bifrost/ms-teams-deploy-card@master
            if: always()
            with:
              github-token: ${{ secrets.GH_ACTION }}
              webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
